sudo: false
dist: bionic
language: node_js
node_js:
  - 8
install:
  - 'cd $TRAVIS_BUILD_DIR'
  - 'yarn install'
script:
  - 'echo $MY_SECRET_ENV'
  - 'cd $TRAVIS_BUILD_DIR'
  - 'yarn test -u'
  - 'yarn build-all'
before_deploy:
  - 'cd $TRAVIS_BUILD_DIR'
  - 'npm install -g firebase-tools firebase-functions firebase-admin'
deploy:
  -
    provider: script
    skip_cleanup: true
    script: 'bash scripts/deploy_staging.sh'
    on:
      all_branches: true
      condition: '$TRAVIS_BRANCH = "develop"'
  -
    provider: script
    skip_cleanup: true
    script: 'bash scripts/deploy_production.sh'
    on:
      all_branches: true
      condition: '$TRAVIS_BRANCH = "master"'
cache:
  npm: true
  directories:
    - node_modules

after_success:
  - 'cd $TRAVIS_BUILD_DIR/_ref/travis-build-merger'
  - id
  - 'sudo apt update'
  - 'sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools'
  - 'pip3 install --user pipenv'
  - 'pipenv sync'
  - 'pipenv run python3 travis-build-merger.py'

notifications:
  slack:
    secure: "jMl3QRRfBTRglD6lVeYQSM+ljUsVp37UUuZixVDAaMvLF9m64GvyCbbc8n8AbojZxn7DpMR1mRvCUc3EmVG4z+wFjpvrfbWNFU/rjvRmoxkSLdbEYtI+4Nk+eZPYe4HjDXNL1M6KLCNBPVGgpaiogYwKCQviaLKUxeo40uW76ceKas1SnzQI6OFU8n25ixj9CNM+4/y4TCHpLvW4DJr7Ud4UaYJRCJPwCQIi0e1s/PRMeGmVixvIne1KmrWV/iQwcmBcPfitluRkDHXV4zyB5KnL9W50hzfksR1ttUYOZniW0lemxrLeEQ/wBkt4OuXxtYwWn5G2kL71PqRM2L+RVGk5Q0o9AJiuUhoifgVzO8kgDK00hjGjpiFdMGj4BgNyYaX6Dv/dy7I7XAOqIOqzTn82PvKm55/NVudYkt6Iu5GU5uOFxCHF+IsBMCMOBl942s0Dp2rEa1bwcUa4twrmqRLRvv2eKeTJSBZWYQ5tHTC6JF8OgoM5SIldqbzqPsueiTPcWj72RnTyGd/l9lV0B3umHwa9KqCRTbF2CGRYog0D131+wy6fRnyKGEPLWsmOI5eA6YQQBo/7kiKvcoVn9u9VWKXzz1+ctTq1i/d2WGA4nZ9uoyU4/9Zj8ZnUgtvVsOsMeao27UaP9Nflg4D2deR51IE0lJTzgNFoc0r30s0="

env:
  global:
    # adding FIREBASE_TOKEN
    - secure: hST9jvb245iispZoZnQB5CKbZP3yuzCb3RTBsnpe69s/Di8GfpZRHQ1QkiP187NLwZvVYyzy2K16UlilzfelnOBpX7eRK4rlPo2/V4jGnuvSsYywIrQoFJ1ByG4f9gfVgFr5juG2APs0eAbQnzCf9FOBRZ9TN6jcEwuU3ldkxGL2e52xZ7h9qgTE958dlh8lGXXbEq7Oa4SZ0Cr7wMxHP6ZlMSNQgKnbEtrPC/ipeqZhZhKArBBVKb960cXd3gWuAzbQoojw2nk5TfDmF2KU10MhEb+Ipey5CBQQRevM8tCFN2TLd2O8/o2xCKk3Xn8Lwxgi0tLTVp9XzEqpRF94htLFJclyMIpHiDoGaLiR+T2u253SbPLXPGk3nPa7BGTNN0TxseTn74E7FQWzJV0B46h5pHMILLUWkTwPLD5FwuG6lhI8Z5aGYUO9wJKjMsdopgkHp41ixa7AgbdALGe6PQk0IxXRpsBhpVtziZt38Tvvv8xiFVWUKCuIv1V6RdutYxCNBzSB/GtNpYxIdVQLQbuoLnKuCWogROl9Io4KGk+PsXXVzEliYOaaG4OHmzviZ6B3s5uBouQGUuUBUNuPSujGdNLhwMFt+wSMeQY8a90IRpPKndnu7KdEcjVZvpMcmJhyGxniHfzpHPZdLzwXYW7sBjXq5AnrydK4s5aLrPw=

    # adding SLACK_TOKEN
    - secure: bBhKG4lOObva0jghM4kWBi5Owvxn2Ti6wrO63MDsixvOAkFFtjP2P8gGw4M1Qymk+1k2EZ0H+X4hrApycDzwdLulqWKvS71emgyd4xtSu27W1ryJNm97sKvmAQw/dpOnoaQ3YTfB+Qs7KRcePOUInmjmv6kVlSCYJ+ddFpFjLbrWxeAwOPz2aq6oHtq9Yp8VWKMuP/I6DCtNBd299yF+jhsy8+FGfMFJKxRdz6TTUYQv/UJP1mecdCrehP8F7jxMUOjUvFBWxBtb14e2vEszJhwXJykLnr2C+o9E37iWzWsYQuilDUXiltYtRXRC/HEZwlR36Dim5ar5eqSEbQGiBgpdJeHYM7ByON6NpVjEK1GYAd5QLYW6wzc40G5vrnKafr2yuUxqsFzP6ifc5cd8ARLiujnYivqpbG90M9hiaRyOO2Pf5EFj4RS6aEeUc3uGrqYxM1hQ1Y4l1vTgvymYfCJNbwDeF9JZHQkgMXzxALohr2HjlmRD4ZVMd3vwVw6L8gmf4e6oKVtkNh3DLZghG0XGUg3qPctmFBDPjlM6vko9CkjywY6IXZ8yH3vV70EOBGZdIEo9KDZRs7pJZEonPae75wT8gPKY4kfJSCkGZIHfKAQ16CzqKaLlVtk4aGooZt+YqvLbIW4YNy53kMdGubirRdasQ6ICYjR9KEe+IJw=

    # adding GITHUB_SECRET_TOKEN
    - secure: M0NKze5g9t8M27qBkvWLc4a4MzOEiXXFyy7lCO3GPsR6pTEwo2nWYKJYWmGf9EvB0uHV44rJloSGXcD9Jgp8dpWuaEVupRy+kVSp2Cor6XINRcSVoSnWFnvWfCnFBDOzzBLAhSNuAan8Ot/vYAG4WM6Ep6Ha8wrGWk128MXvMyNYwxHxhJodwR8pvT0wjRy/WYJZtAHeoVqB8Qp58FH/AmEIlSF17oKtrJeEdmaAZmWGLtRLzE4LQMuSQdn6usH7mHJzW0xLK8cQC4W+zJ3eOdEYmLmZe8hS0hAg/yLiPmCnp5pZwf5aEvEzzEPmTJPvVd5/1bGcko4/V8hs5qbsJMeN+MlvgnfokTebIDb8EJbKNycoiPkpge8PQcVNwVuzHAPRRWztAL0axg0kTHlkkYO625h4biIvEHM2Sv7f+QlW3Nt5dWyw31sQ79zCxHO4P9XOboKkxe8LdNnHpkNoTbV90st04CxA6QY6f+hcbYFlQZheXKJeFUnu6w8xBxtIeFKMqcWlYJwdmbud3US6bGlUVB+UhofoVSPkCRWStBLQMHumYEVYXe4+2BsmMc09fCqOwoh5p093pB+H2gIM3gTeROfckaMfEoZEDBe+UJB7dHUDB+S/bggyTASzbgmwJz5PpyWFFekA5eehBCbQkia2JlLUzPZ1NmuL2ovowGM=
