sudo: false
dist: bionic
language: node_js
node_js:
  - 8

import:
  - credentials.yml

install:
  - 'cd $TRAVIS_BUILD_DIR'
  - 'yarn install'
script:
  - 'echo $MY_SECRET_ENV'
  - 'cd $TRAVIS_BUILD_DIR'
  - 'yarn test -u'
  - 'yarn build-all'
before_deploy:
  - 'cd $TRAVIS_BUILD_DIR'
  - 'npm install -g firebase-tools firebase-functions firebase-admin'
deploy:
  -
    provider: script
    skip_cleanup: true
    script: 'bash scripts/deploy_staging.sh'
    on:
      all_branches: true
      condition: '$TRAVIS_BRANCH = "develop"'
  -
    provider: script
    skip_cleanup: true
    script: 'bash scripts/deploy_production.sh'
    on:
      all_branches: true
      condition: '$TRAVIS_BRANCH = "master"'
cache:
  npm: true
  directories:
    - node_modules

after_success:
  - 'cd $TRAVIS_BUILD_DIR/_ref/travis-build-merger'
  - id
  - 'sudo apt update'
  - 'sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools'
  - 'pip3 install --user pipenv'
  - 'pipenv sync'
  - 'pipenv run python3 travis-build-merger.py'
