sudo: false
dist: bionic
language: node_js
node_js:
  - 8
install:
  - cd $TRAVIS_BUILD_DIR
  - yarn install
script:
  - echo $MY_SECRET_ENV
  - cd $TRAVIS_BUILD_DIR
  - yarn test -u
  - yarn build-all
before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - npm install -g firebase-tools firebase-functions firebase-admin
deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy_staging.sh
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH = "develop"
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy_production.sh
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH = "master"

cache:
  npm: true
  directories:
    - node_modules

after_success:
  - cd $TRAVIS_BUILD_DIR/_ref/travis-build-merger
  - id
  - sudo apt update
  - sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
  - pip3 install --user pipenv
  - pipenv sync
  - pipenv run python3 travis-build-merger.py
notifications:
  slack: louislabs:x4D51HjnR30LGpqZXrdbqUgB
env:
  global:
    secure: ZnTdxsHa5+TyDthPkInVF2eX7nF2dk4I5tHs3YUZATBqIpvUqc2eJ0YdF7y0D0G7z+A4VsXTSY3Ry12VaQGLlaXzUAfFNXIis+wuOZNcymHijxuEAYF8+AcJSk8k9p6pjuABLNR+/cSs6kT7j4RyQFvy9nZJBaX/QEJzf2CSDc1/aHkCyhAsCzkmMQkwc48WcTd8MnY3Jlk6wh/Jc0XRJOrgA7iNgY4+2fDmj6sjWK74zChJhntdkw+FS2jfGwNHc59Nk9EB7cRkgnQV/UWMXk56JPL+qaRgbRh5Ae3SOCh73Jb1CRhmPZxN6sqHU5hdEDr3XfrmQ7vj/8Jx35rzTK7SMG2yGnkRBSkc/3BgGyyjK8meGdUwXm7t1JE65cfX5n+YTRuiXiRMUcxlrvcC4Rj7hZTNBRpAF18E+SGkb2iubxOvIckP/JYhACinEPGqg/aTndIpDzt/0KW5eZuoAmonkjslUN73HfbSaL3Ge3m5Ym50YNH+3Bu3KsoW3N3NpKufYVTlmmUfyvIqiT4YjCahB2C0TpHsXWDLQkgy7gA1sDP9cxn54kdPJhZObxArzPbATl6otBOxMb7gce4ezmGHeNV5VXX6E7qNMBwzY08HljWL9DakQECMFvosc3jgrY3uyGCQCly4AQMnpyN4f5xf4z3FMfcgrDDa0Q3Sg0U=
