#.travis.yml
sudo: false

dist: trusty

language: node_js

node_js:
  - 8

install:
  - yarn install

script:
  - cd $TRAVIS_BUILD_DIR
  - yarn test

before_deploy:
  - yarn predeploy
  - npm install -g firebase-tools firebase-functions firebase-admin

deploy:
  # staging deploy
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh

    on:
      all_branches: true
      condition: $TRAVIS_BRANCH = "test/travis-upload"
#   # production deploy
#   - provider: script
#     skip_cleanup: true
#     script: firebase deploy --project $FIREBASE_PROJECT --token $FIREBASE_TOKEN --non-interactive
#     on:
#       all_branches: true
#       condition: $TRAVIS_BRANCH = "master"

cache:
    npm: true
    directories:
        - node_modules

notifications:
  slack: louislabs:x4D51HjnR30LGpqZXrdbqUgB
