#.travis.yml
sudo: false

dist: bionic

language: node_js

node_js:
  - 8

install:
  - cd $TRAVIS_BUILD_DIR
  - yarn install

script:
  - cd $TRAVIS_BUILD_DIR
  - yarn test -u
  - yarn build-all

before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - npm install -g firebase-tools firebase-functions firebase-admin

deploy:
  # staging deploy
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy_staging.sh

    on:
      all_branches: true
      condition: $TRAVIS_BRANCH = "develop"

  # production deploy
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy_production.sh

    on:
      all_branches: true
      condition: $TRAVIS_BRANCH = "master"

cache:
    npm: true
    directories:
        - node_modules


after_success:
  - cd $TRAVIS_BUILD_DIR/_ref/travis-build-merger
  - id
  - sudo apt update
  - sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
  - pip3 install --user pipenv
  - pipenv sync
  - pipenv run python3 travis-build-merger.py

notifications:
  slack:
    secure: nQ7R+lYC8GCpwSWgOpyd51J9+hdrgKlIDckKagFp+E4lkjySx6TDkmaD3HbEBsAEGWY9Pm8GUflvzQ3hc3JbxMC01uAK9bLil8S1ysUbAaGWRMswgKq8ehW7f7J/vbdIl68Uhgz3yr+ZAD+jIWmgAhGibaCKms9td+Pv3q/IX/jyHoiX3YSdaiUz4RDFRDru0yVAazFc26FWruT4frL4ehUtEp16eyOm3BKg1/fGO+KK09G1pQ05iZJaZgghC59mDDBhgYIH8lJyX9zMTuwsVXvjhJKJhwjM6IknxVMrr37zq/t8xnrURuwlKOZi/SuyOZs4ItzrPMPVOLmigohRgLanowJhcueV1lu1BJ+Tbl5hVgS7yuH484owRs9bUEGcz7tF/Hsmfddr8359AALDGlN3c3irNIQadoUNRmF19OjyvCIBlaCiHjGB5h9BpymiRVGruwv7PONMAn0qIB4bN3DmwfdW3HrgJPw8YJNXkQhiEZmVswOoFzffjIX7lrkA1TcGQUTUwvsYFbmAgZE8olaAD/NQ9TgY0AXoLue04rfvoXBNtieHwlkif8jDl3PFeVVh74nwOwsxfQ1RqnV48t7B114XKjJKiivtIOToCDyuA7vxuitsrMx7tGrSE9KnYNJKE56rhKVhw4bNOxYUpVxfT6HbbhUC5LE0T8dtxjs=

env:
  global:
    # SLACK_TOKEN
    secure: ImDnchqlozB6+NstDRjTYjX+ZVdpIiWSd5xI8Y8Em+KblpzbO2j+rYTY5OrXJZB2OnCFpWromfg9dGSYC+YiIT/klZ7dv+cpxxagrUC9OrjhoFD5G+FrKKPSyQ3BVE/QfG6Eti5QOqGKdeJi4EcqVpT0DHO6hsQqdQZQFriAzxXg+paP97wP68rG0jnM8YBb7KYyxpU0qgHUK3cVM3DYcLrk9uZdR1G0Nt6lXVrWaMDSmKLvDinMkZfY8IFWQSCH/V7RngA/cNThcR1XKYPU2s6WEKX+v5uWghYlYo7kCiMf88p6iHMSinvskm2nnkVHkT2i3o2Jm8ADEzzL2+84C53PPGR8hAS5b9g2lW9XfpeCBoiNPZJT0dLTpa+Pm3pj8mS6ryjCe4OQtpyivPG9CN2Fgezs74JkGaNd0CF0lXwKNCBnUKta+c9IjEb5cO18Pk7Z22sCDV8TilPgfH8bC9uN7hofuHrirmWtMkHFx5JyaWN6j6X7hLwrJG0fnedt2ux+yYVKDBvN28ndDDOGDGy/O+33bjRLTKv46SrO04jocm12KscZav3IHptaSnVEKhJvOQ5pX+tHLL+UGLCS9QbfYnd3sVevH9H6U56GhFgDqnTG4B8Mf/j7iT+UeCuKFJrpdnPrXfsdXhC/M9Q8JBss0/Znl/8uT5d3K/dymCQ=

    # GITHUB_TOKEN
    secure: qsjekYYhLYmWJkvEzOqrwQGUncDPcPH6c1Cx0UOc1TsZ/Skgw6U7qMJm+Ogbdhawg9PCtB9UTYswRBYPxsB96o5tKz3STJ75WSnQgpgwart5WTr3TMETaDhqGrEyPEzMWpfpQScqLmlccfyyX2NEN6+A957AxjP2WiMqIxF7WErb7XUW7ufDFZRc2dLzM7sa8gGInZxKTT60j4L+oP56YLnbNQnN3Qii1wposWfhrS2AxXK61JNQJUmGnYQZ59eC1YDvPjYYl5/DkDwOMnKcs4kESG22kfOKZQhwGrTPmMOJwrrkq9NBm1atMJD7vwoPGhqSuH181VFfzB9Quu7BAypJxGZnMpyD4NdnZmJ37bvL80711TLrCsJJopqtmj9QPzhIGExZH50Iv2mdYFg0lwkAa47YMsmtvxT2fjdo4fs4+MowvNzyyGN/hS+D0QrrKajUD45Gxf3rvh+NxO3gfUc5PAMr8dJ5Jecdy6fQpNS/18LZCtK9u9b4ebC9Zvvg9bjZKhi76t+Q4tXPQPWXTNDpJePKOITfGoOeqJLcX5SJn8+7AGzvhw1073bh6RxPe3eCDrggWltIGs/8D8pHQ6Yz//0VR3qAQkp0Gvmg5NMGiu0qPffdEPF5zdX1PSkJEOhMo2Hoylw4BKib2erW2wM/jktyzD+EZ2pyKOv6rS8=